### ISSUE TITLE
CMVN in raw_fbank_pitch_all files

### ISSUE THREAD

**Issue by dannigt** [srvk/how2-dataset#10]
Hi, a related question was asked [before](https://github.com/srvk/how2-dataset/issues/9).

I'm aware that the features used in your [paper](https://arxiv.org/pdf/1811.00347.pdf) are 40-dimensional fbank + pitch with per-video Cepstral Mean and Variance Normalization.

What I'm wondering is about the features in the compiled dataset, more specifically those ones in "`raw_fbank_pitch_all_181506...`", are they before or after CMVN?
```
fbank_pitch_181506/
├── cmvn_all_181506.ark
├── cmvn_all_181506.scp
├── raw_fbank_pitch_all_181506.10.ark
├── raw_fbank_pitch_all_181506.10.scp
├── raw_fbank_pitch_all_181506.1.ark
├── raw_fbank_pitch_all_181506.1.scp
├── raw_fbank_pitch_all_181506.2.ark
├── raw_fbank_pitch_all_181506.2.scp
├── raw_fbank_pitch_all_181506.3.ark
├── raw_fbank_pitch_all_181506.3.scp
├── raw_fbank_pitch_all_181506.4.ark
├── raw_fbank_pitch_all_181506.4.scp
├── raw_fbank_pitch_all_181506.5.ark
├── raw_fbank_pitch_all_181506.5.scp
├── raw_fbank_pitch_all_181506.6.ark
├── raw_fbank_pitch_all_181506.6.scp
├── raw_fbank_pitch_all_181506.7.ark
├── raw_fbank_pitch_all_181506.7.scp
├── raw_fbank_pitch_all_181506.8.ark
├── raw_fbank_pitch_all_181506.8.scp
├── raw_fbank_pitch_all_181506.9.ark
├── raw_fbank_pitch_all_181506.9.scp
```

Many thanks for publishing this dataset, and thanks in advance for your help!

Danni

**Comment by ramonsanabria** [comment]
Hi Danni,

Yes, the raw_* means that they have not been normalized.
