### ISSUE TITLE
issue when running scripts/install.sh -j 16

### ISSUE THREAD

**Issue by MOoNAaaa** [srvk/how2-dataset#11]
```
root@703b777a4652:/work/how2-dataset/reproduce/300h# scripts/install.sh -j 16
scripts/install.sh: line 59: curl: command not found
Last available 
Temporary folder: /tmp/tmp.cgXDljMOWW
# of outstanding downloads: 13493
[Attempt #1] 13493 subtitles to download.
0% 0:13493=0s -0f-dGNMoGc                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 1:13492=0s -0gE556zuqg                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 2:13491=0s -0jwUa8LuGE                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 3:13490=0s -0oP2H0vAGY                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 4:13489=0s -0sphqZT1eQ                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 5:13488=0s -0yRaqY7nTE                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 6:13487=2247s -17sKcaMGrI                                                                                                                                                                                ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 7:13486=2247s -19u3X85sRc                                                                                                                                                                                ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 8:13485=2246s -1KpdDGPCq4  
```
root@703b777a4652:/work/how2-dataset/reproduce/300h# scripts/install.sh -j 16
scripts/install.sh: line 59: curl: command not found
Last available 
Temporary folder: /tmp/tmp.cgXDljMOWW
[Attempt #1] 13493 subtitles to download.
0% 0:13493=0s -0f-dGNMoGc                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 1:13492=0s -0gE556zuqg                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 2:13491=0s -0jwUa8LuGE                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 3:13490=0s -0oP2H0vAGY                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 4:13489=0s -0sphqZT1eQ                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 5:13488=0s -0yRaqY7nTE                                                                                                                                                                                   ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 6:13487=2247s -17sKcaMGrI                                                                                                                                                                                ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 7:13486=2247s -19u3X85sRc                                                                                                                                                                                ERROR: Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'),))
0% 8:13485=2246s -1KpdDGPCq4

**Comment by MOoNAaaa** [comment]
I run it with youtube-dl 2019.10.22
I am in china, and use shadowsocks to flip the wall，I can access youtube normally.

**Comment by MOoNAaaa** [comment]
the issue shows scripts/install.sh: line 59: curl: command not found
and scripts/install.sh: line 59 is :
echo "Last available `curl -s http://islpc21.is.cs.cmu.edu/ramons/version`"

**Comment by ozancaglayan** [comment]
Hi,

That error is not that important but you need to have `curl` installed to make it go away. But more importantly, your connection to youtube seems to be refused. We use `youtube-dl` to download the video files. It is likely that you need to configure youtube-dl so that it knows about your proxy/vpn settings.
