### ISSUE TITLE
Multi Model Summarisation code?

### ISSUE THREAD

**Issue by buddiesknock** [srvk/how2-dataset#14]
Hey I can't trace the code for multi model summarization. Is it publicly available ?

**Comment by xiang-xiang-zhu** [comment]
Hello,I only saw two paragraphs. How should I train? Is there any config designed for Summarisation??

**Comment by ramonsanabria** [comment]
if you have the data, it should be the same thing as nmt-* baselines, but changing the input and target files and (if needed) parameters.
