### ISSUE TITLE
Vocabulary file

### ISSUE THREAD

**Issue by blazingcanon1** [srvk/how2-dataset#15]
The number of vocabulary is 5001 in baseline logs.
I generated vocabulary files with reference to prepare-howto-480h.sh
However, the number of vocabulary is 78123 in my logs.
Could you tell me how to generate vocabulary files and what data is contained?

**Comment by ozancaglayan** [comment]
this is because we used a SentencePiece vocabulary of 5000 tokens.

**Comment by blazingcanon1** [comment]
Thank you for your reply.
I generated vocabulary files by using SentencePiece, but nmtpy vocabulary files include pieces, treated as "unk" in SentencePiece, like "6789" and "=".
The number of vocabulary became 5103.
I generated vocabulary files by using commands below.

`spm_train --input=text.en --model_prefix=spm --vocab_size=5000`
`spm_encode --model=spm.model < text.en > text.spm.en`
`nmtpy-build-vocab text.spm.en`

how can I correct it?

**Comment by ozancaglayan** [comment]
the only different argument that we've passed to `spm_train` is `--character_coverage 1`. This may be related to SPM version, or some other stuff. Aren't you using pre-extracted package of features which already have the SPM'ed files? Why do you need to re-create them?

**Comment by blazingcanon1** [comment]
I didn’t realize it contains SPMed files.
Is it "text.en" in "English text" parts that can be downloaded through the form?
It looks like it's not lowercased or tokenized.
