### ISSUE TITLE
Questions about the extracted video features of the how2 dataset

### ISSUE THREAD

**Issue by balabanahei** [srvk/how2-dataset#16]
In the How2 dataset paper, it mentioned: "A 2048-dimensional feature vector per 16 frames is extracted from the videos using a CNN trained to recognize 400 different actions". Is the pre-training model in the original paper for extracting How2 video features publicly available on https://github.com/kenshohara/3D-ResNets-PyTorch? Or is your model trained on your own based on the Kinetics dataset for extracting How2 video features?

**Comment by ozancaglayan** [comment]
No we used the publicly available extractor and did not re-train it.
