### ISSUE TITLE
Extracting audio, video and text features for new dataset.

### ISSUE THREAD

**Issue by buddiesknock** [srvk/how2-dataset#17]
Hi,

I want to try the How2 model on my own videos and transcript but the reproduceable pipeline readme says that I need to pass through Step 1 to get some pre-extracted features.

Can you please let me know how can I extract features for a new YouTube video?

**Comment by ramonsanabria** [comment]
Hello,

Youtube videos are no longer available (the user removed them from the
channel). The option available is to get the prextracted ones.

**Comment by buddiesknock** [comment]
Thanks for reply, But my issue is about newly extracted YouTube videos that are different from the current how2 dataset.

I have videos and transcripts with me and I want to know if is their a script to process these videos.

**Comment by roshansh-cmu** [comment]
It depends on what features would need to be extracted. Tools like Kaldi or Librosa can be used to generate speech features.
