### ISSUE TITLE
Question about the video feature and segment file for entire set

### ISSUE THREAD

**Issue by xixihahaggg** [srvk/how2-dataset#19]
I've requested the video feature from the form. I'm just wondering about the format of the video feature. To my understanding, the video feature covers the entire temporal sequence, where the audio will skip the blank (non-speech part). I'm just wondering if it is possible to obtain the video feature for each segment (like audio) using the existing segments file? For example from the paper, per video features represent 16 frames. Then we can use this info to do the alignment. So my question is, how long time is per frame or how many frames per second for the video since it did not mention in the paper. 
Also, I saw that it performs a good alignment for the 300h subset, so the for the rest 1700h are skipped because of the bad alignment. Could you please share the segment file for the rest 1700h subset? 
Thank you!

**Comment by ramonsanabria** [comment]
Hello, 

- Re the action features.  The original extraction gets a vector every 16 frames and then they are averaged for each segment (as explained in the paper). 

- Re audio. There is no VAD (i.e., removing the non-speech part) or diaritzation happening. We obtain an audio representation of 25 ms every 10 ms (as explained in the paper).


Re the rest of the dataset, and video. Can you send this in an email.

Thanks.

**Comment by xixihahaggg** [comment]
> Hello,
> 
> * Re the action features.  The original extraction gets a vector every 16 frames and then they are averaged for each segment (as explained in the paper).
> * Re audio. There is no VAD (i.e., removing the non-speech part) or diaritzation happening. We obtain an audio representation of 25 ms every 10 ms (as explained in the paper).
> * Re the rest of the dataset, and video. Can you send this in an email.
> 
> Thanks.

Hi,  Thank you for your reply! 

Sorry for the confusion, I understand that in the reproduce 300h you use a single average pooled vector to indicate the whole sequence of vectors. But I'd like to use the sequence vectors in my experiment. So I want to know if it is possible to segment the video features into sentence-level (sentence segments) out of an entire video. I believe that audio has the features for sentence-level but video features are video-level. By the way, how to reach out to you, I've sent a request through the how2challenge email.

Best.

**Comment by ramonsanabria** [comment]
hello write me at ***@***.***

**Comment by xixihahaggg** [comment]
Hi, the email is censored by Github, I find the email on your personal website. Did you receive that email?

**Comment by ramonsanabria** [comment]
here is my website: https://homepages.inf.ed.ac.uk/s1945848/index.html you
should be able to find my email there
