### ISSUE TITLE
Which BLEU is being reported as the baseline for MT?

### ISSUE THREAD

**Issue by Demfier** [srvk/how2-dataset#2]
Hi,

First off, thanks for such a nice dataset, however, I was wondering which BLEU is being reported as the baseline for MT. I assumed it would be BLEU-1 but it would good have a confirmation from your side.

Thanks.
Gaurav.

**Comment by ozancaglayan** [comment]
Hi,

Thank you! The BLEU scores reported in the paper are BLEU-4 scores not BLEU-1.

**Comment by Demfier** [comment]
Oh, alrighty! Thank you for the clarification.
