### ISSUE TITLE
BLEU is 0 when i run nmt config

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [srvk/how2-dataset#21]
I downloaded the file, unzipped it and got several folders. I'm going to use the config file you provided to reproduce it, but Bleu is 0 for machine translation

The language files use text.en and text.pt in the data folder under how2-300h-v1. I see that the config and log files provided by you are processed by spm5000. I don't know if this is the problem

[train]
seed: 0
model_type: NMT
patience: 10
max_epochs: 100
eval_freq: 0
eval_metrics: bleu,loss
eval_filters: de-spm
eval_beam: 5
eval_batch_size: 256
save_best_metrics: True
n_checkpoints: 0
l2_reg: 0
gclip: 1
optimizer: adam
lr: 0.0004
lr_decay: plateau
lr_decay_revert: False
lr_decay_factor: 0.5
lr_decay_patience: 2
batch_size: 256
save_path: save_nmt
tensorboard_dir: ${save_path}/tb_dir

[model]
att_type: mlp
att_bottleneck: hid
emb_dim: 320
enc_dim: 320
dec_dim: 320
n_encoders: 2
dropout_emb: 0.3
dropout_ctx: 0.3
dropout_out: 0.3
tied_emb: 2way
dec_init: mean_ctx
direction: en:Text -> pt:Text
bucket_by: en
max_len: 120

[data]
root: how2-300h-v1

train_set: {'en': '${root}/data/train/text.en',
            'pt': '${root}/data/train/text.pt'}

val_set: {'en': '${root}/data/val/text.en',
          'pt': '${root}/data/val/text.pt'}

dev5_set: {'en': '${root}/data/dev5/text.en',
           'pt': '${root}/data/dev5/text.pt'}

[vocabulary]
en: ${data:root}/data/train/text.vocab.en
pt: ${data:root}/data/train/text.vocab.pt

Loss can drop normally, but Bleu is always 0,How should I solve it, thank you

**Comment by ramonsanabria** [comment]
hello, what "Bleu is 0" mean?

**Comment by xiang-xiang-zhu** [comment]
At the end of the program, loss can be reduced to very low, but the bleu is still 0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "srvk/how2-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月7日(星期六) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [srvk/how2-dataset] BLEU is 0 when i run nmt config (#21)





 
hello, what "Bleu is 0" mean?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
