### ISSUE TITLE
how to get the raw video 

### ISSUE THREAD

**Issue by zhenzliu** [srvk/how2-dataset#22]
i tried to use the the script 'how2-dataset/reproduce/300h/scripts/install.sh', it seems that  the videos have been removed. So have all the videos been removed? Is there any other way to get the video data?

 thanks for your help!

**Comment by ramonsanabria** [comment]
hello, can you write me at ***@***.***? Thanks!

**Comment by ramonsanabria** [comment]
you can request the prepared dataset here:
https://docs.google.com/forms/d/e/1FAIpQLSfW2i8UnjuoH2KKSU0BvcKRbhnk_vL3HcNlM0QLsJGb_UEDVQ/viewform

If you need more info get my email here:
https://homepages.inf.ed.ac.uk/s1945848/index.html we can chat there :)

**Comment by ramonsanabria** [comment]
write me here: https://homepages.inf.ed.ac.uk/s1945848/index.html
