### ISSUE TITLE
Video download & others

### ISSUE THREAD

**Issue by chlorane** [srvk/how2-dataset#25]
I upgraded to the recent version of youtube-dl, but when I run install.sh with "scripts/install.sh -j 16" command, there is always a message saying "ERROR: Video unavailable"
Like this: 
0% 0:9694=0s -19u3X85sRc
ERROR: Video unavailable
0% 1:9693=0s -1PeVdIwiq0
ERROR: Video unavailable
0% 2:9692=0s -1Uik-vwQoc
ERROR: Video unavailable

I tried many times, the same thing keeps happen, nothing are downloaded. What's wrong?

Also, I'm not very sure how to reproduce the code. How can I run the script to get the results in your article?

**Comment by roshansh-cmu** [comment]
The video was likely deleted from YouTube by the original poster- unfortunately, it appears that such videos cannot be downloaded.
