### ISSUE TITLE
Regarding How2 dataset

### ISSUE THREAD

**Issue by prasadmagdum04** [srvk/how2-dataset#26]
I downloaded English transcript and English abstractive summaries from given link. But I am not able to use them for transcript summarization. Means i am not able to separate the transcripts from each other. They all are stored in one huge file without any separation between them. Please help me.

**Comment by ramonsanabria** [comment]
transcripts for sumaritzation are aligned at the video level. If you really want to have sentence-level alignment you can run a force aligner. 

Thanks
