### ISSUE TITLE
how to get the raw video

### ISSUE THREAD

**Issue by zhengzehong331** [srvk/how2-dataset#28]
i tried to use the the script 'how2-dataset/reproduce/300h/scripts/install.sh', it seems that the videos have been removed. So have all the videos been removed? Is there any other way to get the video data?

thanks for your help!

**Comment by ramonsanabria** [comment]
Hello, we can provide raw videos due to copyright licence. But we offer pre-processed features submitting submitting the form specified in the readme file.
