### ISSUE TITLE
Query related to pre-processing

### ISSUE THREAD

**Issue by Demfier** [srvk/how2-dataset#3]
Hi,

It is mentioned in the paper that a SentencePiece vocab of size 5K was created for both, English and Portuguese. So was something like `max_length` was set for the sentences or did you use all the sentences and replaced the OOV words with `<unk>` token?

Thanks in advance!
Gaurav.

**Comment by ozancaglayan** [comment]
Hi,

No this is the [SentencePiece](https://github.com/google/sentencepiece) segmentation algorithm which produces ~5K subwords for open vocabulary generation.

**Comment by Demfier** [comment]
@ozancaglayan - Thanks for the response. I think I understand now - *SentencePiece* doesn't build a word-level vocab. Instead, it uses subword algorithms to build a vocab that arguably supports open vocab generation.

Thanks again :smile:
