### ISSUE TITLE
Issue: Unable to Download Complete Video and Subtitle Data from How2 Dataset

### ISSUE THREAD

**Issue by T0RA1107** [srvk/how2-dataset#32]
After running the install.sh script, I was only able to download 50 hours of videos out of the 300 hours available. Additionally, the intersection between the downloaded videos and the subtitles is empty, meaning I cannot access the paired video and text data.

During the execution of the scripts, I encountered the following error for almost every video:

`ERROR: This video is unavailable`

I have already submitted the data request form but have not received any response for over a week. The raw audio and text data, especially sentence-level splits, are critical for my project.

Furthermore, the How2 dataset is essential for me because I rely on it for accessing the How2Sign dataset, which depends on the How2 dataset.

I would greatly appreciate your assistance in addressing this issue as soon as possible. If it’s possible to provide a partial set of raw videos and subtitles, that would also be extremely helpful.

Thank you for your time and support.

**Comment by Junzizaiji** [comment]
Hello, pls is your problem solved

**Comment by ramonsanabria** [comment]
hello, We experienced issues with the data distribution. We are working to resolve it — apologies for the inconvenience.

we will keep you posted.

**Comment by fmetze** [comment]
Please see updated README - we are unable to provide a copy of the corpus at this time.
