### ISSUE TITLE
Request for Access to How2Dataset for Thesis Research

### ISSUE THREAD

**Issue by surya-parthipan** [srvk/how2-dataset#33]
Hi, I submitted the request form for access to the How2Dataset to support my thesis research on audio summarization.

I haven’t received any confirmation or access details yet, so I wanted to follow up through this channel. Access to the dataset is crucial for my work, and I would greatly appreciate any assistance you can provide.

**Comment by ramonsanabria** [comment]
Hello, we experienced issues with the data distribution. We are working to resolve it — apologies for the inconvenience.

we will keep you posted.

**Comment by fmetze** [comment]
Please see updated README - we are unable to provide a copy of the corpus at this time.
