### ISSUE TITLE
ERROR:Integrity Test failed

### ISSUE THREAD

**Issue by parsrini** [srvk/how2-dataset#6]
Last available version: 1.0
scripts/install.sh: line 72: [: -gt: unary operator expected

scripts/install.sh: line 85: [: -gt: unary operator expected

Verifying the integrity of VTT files
#########################################
~/brazil_workspace/how2-dataset/reproduce/300h ~/brazil_workspace/how2-dataset/reproduce/300h
ERROR: Integrity check failed. Please create an issue with the /var/folders/q5/k0skkt8j73s19464fq45_16cwp836_/T/tmp.mfDBOD6g attached.

with the following errors
gsha1sum: subtitles/G3HKHxevpFI.en.vtt: No such file or directory
subtitles/G3HKHxevpFI.en.vtt: FAILED open or read
gsha1sum: subtitles/G3IJAoK0uSE.en.vtt: No such file or directory
subtitles/G3IJAoK0uSE.en.vtt: FAILED open or read
gsha1sum: subtitles/g3jQ5ecjGz8.en.vtt: No such file or directory
subtitles/g3jQ5ecjGz8.en.vtt: FAILED open or read
gsha1sum: subtitles/G3k86AVFwVs.en.vtt: No such file or directory
subtitles/G3k86AVFwVs.en.vtt: FAILED open or read
gsha1sum: subtitles/g3kFAmcBpFc.en.vtt: No such file or directory
subtitles/g3kFAmcBpFc.en.vtt: FAILED open or read
gsha1sum: subtitles/G3OMdQo1zjY.en.vtt: No such file or directory
subtitles/G3OMdQo1zjY.en.vtt: FAILED open or read
gsha1sum: subtitles/g3PBeTb1TCw.en.vtt: No such file or directory
subtitles/g3PBeTb1TCw.en.vtt: FAILED open or read
gsha1sum: subtitles/g3pXM5X3_Xw.en.vtt: No such file or directory
subtitles/g3pXM5X3_Xw.en.vtt: FAILED open or read
gsha1sum: subtitles/G3qZW-hZXaQ.en.vtt: No such file or directory
subtitles/G3qZW-hZXaQ.en.vtt: FAILED open or read
gsha1sum: subtitles/G3RvsnzQrXQ.en.vtt: No such file or directory
subtitles/G3RvsnzQrXQ.en.vtt: FAILED open or read
gsha1sum: subtitles/g3sLd8JupoQ.en.vtt: No such file or directory
subtitles/g3sLd8JupoQ.en.vtt: FAILED open or read
gsha1sum: subtitles/g3UE1iPiyuE.en.vtt: No such file or directory
subtitles/g3UE1iPiyuE.en.vtt: FAILED open or read
gsha1sum: subtitles/g3ushtMfLiY.en.vtt: No such file or directory
subtitles/g3ushtMfLiY.en.vtt: FAILED open or read
gsha1sum: subtitles/g3V0BsmDUgY.en.vtt: No such file or directory
subtitles/g3V0BsmDUgY.en.vtt: FAILED open or read
gsha1sum: subtitles/G3VM7etNABI.en.vtt: No such file or directory
subtitles/G3VM7etNABI.en.vtt: FAILED open or read
gsha1sum: subtitles/g3wQOQH1vyE.en.vtt: No such file or directory
subtitles/g3wQOQH1vyE.en.vtt: FAILED open or read
gsha1sum: subtitles/g3X3XE6M2_A.en.vtt: No such file or directory
subtitles/g3X3XE6M2_A.en.vtt: FAILED open or read
gsha1sum: subtitles/g3ZgF8gdfLo.en.vtt: No such file or directory
subtitles/g3ZgF8gdfLo.en.vtt: FAILED open or read
gsha1sum: subtitles/g3ZluRtRXVc.en.vtt: No such file or directory
subtitles/g3ZluRtRXVc.en.vtt: FAILED open or read
gsha1sum: subtitles/G42xKICVj9U.en.vtt: No such file or directory
subtitles/G42xKICVj9U.en.vtt: FAILED open or read
gsha1sum: subtitles/-g45vqccdzI.en.vtt: No such file or directory
subtitles/-g45vqccdzI.en.vtt: FAILED open or read
gsha1sum: WARNING: 13492 listed files could not be read

**Comment by shrutijpalaskar** [comment]
Hi @parsrini, I tried to reproduce your error but wasn't able to. Can you give more details about the procedure you followed? Was the installation of all requirements successful?

**Comment by ozancaglayan** [comment]
I do not have access to mac os x, @shrutijpalaskar did you try on mac os x as well?

**Comment by ozancaglayan** [comment]
Closing because of lack of feedback
